[project]
name = "url-crawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "playwright>=1.54.0",
    "requests>=2.32.4",
]
